Ibw\JobeetBundle\Entity\User:
    type: entity
    table: user
    id:
        id: integer
        generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255